---
  - name: copy GenIntAuth
    become: true
    ansible.builtin.copy:
      src: GenIntermediateAuthority.sh
      dest: /ca-stuff/
      owner: ortsoc-admin
      group: ortsoc-admin
      mode: 0774
    when: ca_type == "int"
    
  - name: copy GenP12Cert
    become: true
    ansible.builtin.copy:
      src: GenerateP12Cert.sh
      dest: /ca-stuff/
      owner: ortsoc-admin
      group: ortsoc-admin
      mode: 0774
    when: ca_type == "int" 
    
  - name: copy GenCert
    become: true
    ansible.builtin.copy:
      src: GenerateCertificate.sh
      dest: /ca-stuff/
      owner: ortsoc-admin
      group: ortsoc-admin
      mode: 0774
    when: ca_type == "int"
      
  - name: run GenIntAuth
    become: true
    shell: /ca-stuff/GenIntermediateAuthority.sh
    args:
      chdir: /ca-stuff/
    when: ca_type == "int"
      
  - name: fetch IntermediateCA.csr
    become: true
    ansible.builtin.fetch:
      src: /ca-stuff/IntermediateCA.csr
      dest: /tmp/IntermediateCA.csr
      flat: yes
    when: ca_type == "int"
      
