---
  - name: copy Signed Int crt back to Int CA
    become: true
    ansible.builtin.copy:
      src: /tmp/IntermediateCA.crt
      dest: /ca-stuff/
      owner: ortsoc-admin
      group: ortsoc-admin
      mode: 0774
    when: ca_type == "int"
    
#  - name: delete local tmp files
#    delegate_to: localhost
#     command: rm /tmp/IntermediateCA.crt /tmp/IntermediateCA.csr
