---

- hosts: root-auth
  tasks:
  
  - name: copy genRootAuth
    become: true
    ansible.builtin.copy:
      src: GenRootAuthority.sh
      dest: /ca-stuff/
      owner: root
      group: root
      mode: 0755
    
  - name: copy SignIntCsr
    become: true
    ansible.builtin.copy:
      src: "SignIntermediateCSR.sh"
      dest: /ca-stuff/
      owner: root
      group: root
      mode: 0755    

- hosts: int-auth

  tasks:    
  - name: copy GenIntAuth
    become: true
    ansible.builtin.copy:
      src: GenIntermediateAuthority.sh
      dest: /ca-stuff/
      owner: root
      group: root
      mode: 0755
    
  - name: copy GenP12Cert
    become: true
    ansible.builtin.copy:
      src: GenerateP12Cert.sh
      dest: /ca-stuff/
      owner: root
      group: root
      mode: 0755
    
  
  - name: copy GenCert
    become: true
    ansible.builtin.copy:
      src: GenerateCertificate.sh
      dest: /ca-stuff/
      owner: root
      group: root
      mode: 0755
    
    
    
    
    
