---
  
  - name: check if auth has been configured already
    stat:
      path: /ca-stuff/.root_auth_registered
    register: root_auth_configured_file
  
  - name: copy genRootAuth
    become: true
    ansible.builtin.copy:
      src: GenRootAuthority.sh
      dest: /ca-stuff/
      owner: root
      group: root
      mode: 0755
    when: ca_type == "root"

  - name: run GenIRootAuth
    become: true
    shell: /ca-stuff/GenRootAuthority.sh
    args:
      chdir: /ca-stuff/    
    when: >
      ca_type == "root" and
      not root_auth_configured_file.stat.exists
      
  - name: copy SignIntCsr
    become: true
    ansible.builtin.copy:
      src: "SignIntermediateCSR.sh"
      dest: /ca-stuff/
      owner: root
      group: root
      mode: 0755   
    when: ca_type == "root" 
