---

  - name: copy Int CSR to root CA
    become: true
    ansible.builtin.copy:
      src: /tmp/IntermediateCA.csr
      dest: /ca-stuff/
      owner: root
      group: root
      mode: 0666
    when: ca_type == "root"
      
  - name: run sign Int script
    become: true
    shell: /ca-stuff/SignIntermediateCSR.sh
    args:
      chdir: /ca-stuff/  
    when: ca_type == "root"
  
  - name: fetch signed Intermediate crt
    become: true
    ansible.builtin.fetch:
      src: /ca-stuff/IntermediateCA.crt
      dest: /tmp/IntermediateCA.crt
      flat: yes
    when: ca_type == "root"
