---

  - name: check if auth has been configured already
    stat:
      path: /ca-stuff/.root_auth_registered
    register: root_auth_configured_file

  - name: copy Int CSR to root CA
    become: true
    ansible.builtin.copy:
      src: /tmp/IntermediateCA.csr
      dest: /ca-stuff/
      owner: root
      group: root
      mode: 0666
    when: > 
      ca_type == "root" and
      not root_auth_configured_file.stat.exists
      
  - name: run sign Int script
    become: true
    shell: /ca-stuff/SignIntermediateCSR.sh
    args:
      chdir: /ca-stuff/  
    when: > 
      ca_type == "root" and
      not root_auth_configured_file.stat.exists
  
  - name: fetch signed Intermediate crt
    become: true
    ansible.builtin.fetch:
      src: /ca-stuff/IntermediateCA.crt
      dest: /tmp/IntermediateCA.crt
      flat: yes
    when: > 
      ca_type == "root" and
      not root_auth_configured_file.stat.exists
     
  - name: mark int auth as completed
    copy:
      content: "yes"
      dest: /ca-stuff/.root_auth_registered
      force: no
      group: ortsoc-admin
      owner: ortsoc-admin
      mode: 0660     
